name: chatassistantbot
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.01.10=hecd8cb5_0
  - libffi=3.4.2=hecd8cb5_6
  - ncurses=6.4=hcec6c5f_0
  - openssl=1.1.1t=hca72f7f_0
  - python=3.10.10=h218abb5_2
  - readline=8.2=hca72f7f_0
  - sqlite=3.41.1=h6c40b1e_0
  - tk=8.6.12=h5d9f67b_0
  - xz=5.2.10=h6c40b1e_1
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - beautifulsoup4==4.12.2
    - certifi==2022.12.7
    - charset-normalizer==3.1.0
    - dataclasses-json==0.5.7
    - frozenlist==1.3.3
    - greenlet==2.0.1
    - idna==3.4
    - langchain==0.0.134
    - llama-index==0.5.10
    - marshmallow==3.19.0
    - marshmallow-enum==1.5.1
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - numpy==1.24.2
    - openai==0.27.4
    - openapi-schema-pydantic==1.2.4
    - packaging==23.0
    - pandas==2.0.0
    - pip==23.0.1
    - playwright==1.30.0
    - pydantic==1.10.7
    - pyee==9.0.4
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - pytz==2023.3
    - pyyaml==6.0
    - regex==2023.3.23
    - requests==2.28.2
    - setuptools==65.6.3
    - six==1.16.0
    - soupsieve==2.4
    - sqlalchemy==1.4.47
    - tenacity==8.2.2
    - tiktoken==0.3.3
    - tqdm==4.65.0
    - typing-extensions==4.5.0
    - typing-inspect==0.8.0
    - tzdata==2023.3
    - urllib3==1.26.15
    - wheel==0.38.4
    - yarl==1.8.2
